const seed = {
  business: { name: 'Mitti & Co.', category: 'Restaurant / QSR', stage: 'Pre-launch', budget: 1800000, launch: '2026-10-15' },
  items: [
    { id: 1, module: 'Compliance', name: 'FSSAI registration', status: 'In progress', estimate: 12000, committed: 8000, paid: 4000, due: '2026-08-18' },
    { id: 2, module: 'Location', name: 'Kitchen & counter layout', status: 'Completed', estimate: 65000, committed: 62000, paid: 62000, due: '2026-08-12' },
    { id: 3, module: 'Equipment', name: 'Commercial kitchen equipment', status: 'Quoting', estimate: 420000, committed: 0, paid: 0, due: '2026-08-25' },
    { id: 4, module: 'Furniture', name: 'Customer seating & tables', status: 'Not started', estimate: 210000, committed: 0, paid: 0, due: '2026-09-05' },
    { id: 5, module: 'Team', name: 'Hire kitchen lead', status: 'In progress', estimate: 45000, committed: 0, paid: 0, due: '2026-08-20' },
    { id: 6, module: 'Branding', name: 'Signage & menu design', status: 'Completed', estimate: 30000, committed: 30000, paid: 15000, due: '2026-08-16' }
  ],
  vendors: [{id: 1, name: 'Urban Kitchen Systems', category: 'Equipment', person: 'Arjun Shah', phone: '+91 98765 43210'}, {id: 2, name: 'Form & Function Studio', category: 'Interiors', person: 'Nisha Rao', phone: '+91 99887 66554'}],
  tasks: [{id: 1, title: 'Review FSSAI document checklist', module: 'Compliance', due: '2026-08-18', status: 'To do'}, {id: 2, title: 'Compare kitchen equipment quotes', module: 'Equipment', due: '2026-08-14', status: 'To do'}, {id: 3, title: 'Approve final signage artwork', module: 'Branding', due: '2026-08-16', status: 'Done'}]
};
let state = JSON.parse(localStorage.getItem('plansupe-data') || 'null') || structuredClone(seed);
let screen = 'home';
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n || 0);
const save = () => localStorage.setItem('plansupe-data', JSON.stringify(state));
const esc = s => String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const svg=(path)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`;
const icon = {
  home:svg('M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3Z'),
  tasks:svg('m4 12 4 4L20 5'),
  vendors:svg('M16 20v-1.5a4.5 4.5 0 0 0-9 0V20M11.5 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm6-2.5a3 3 0 0 1 0 6'),
  more:svg('M4 6h16M4 12h16M4 18h16')
};
function totals(){ const committed=state.items.reduce((a,x)=>a+x.committed,0), paid=state.items.reduce((a,x)=>a+x.paid,0), forecast=state.items.reduce((a,x)=>a+Math.max(x.committed,x.estimate),0); return {committed,paid,forecast,outstanding:committed-paid}; }
function readiness(){ return Math.round((state.items.filter(x=>x.status==='Completed').length / state.items.length)*100) || 0; }
function nav(){ return `<nav>${['home','tasks','vendors','more'].map(x=>`<button class="${screen===x?'active':''}" onclick="go('${x}')"><span>${icon[x]}</span>${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav>`; }
function header(title, sub=''){ return `<header><div><p class="eyebrow">${sub || 'Plan, launch & operate'}</p><h1>${title}</h1></div><button class="avatar" aria-label="Account">PS</button></header>`; }
function cardItem(x){ return `<article class="record"><div class="record-top"><span class="module">${esc(x.module)}</span><span class="chip ${x.status.toLowerCase().replaceAll(' ','-')}">${esc(x.status)}</span></div><h3>${esc(x.name)}</h3><p>${money(x.committed || x.estimate)} ${x.committed ? 'committed' : 'estimated'} · Due ${x.due}</p><div class="actions"><button onclick="cycleItem(${x.id})">Update status</button><button onclick="payment(${x.id})">Record payment</button></div></article>`; }
function home(){ const t=totals(), active=state.items.filter(x=>x.status!=='Completed'); return `${header('Good morning, Priya','Your business workspace')}<section class="business-hero"><div><span class="hero-tag">${state.business.stage}</span><h2>${esc(state.business.name)}</h2><p>${esc(state.business.category)} · Launch ${state.business.launch}</p></div><button onclick="go('business')" aria-label="Open business">${svg('m9 18 6-6-6-6')}</button></section><section class="readiness"><div class="ring" style="--ready:${readiness()}"><b>${readiness()}%</b><span>ready</span></div><div><h2>Launch readiness</h2><p>${state.items.filter(x=>x.status==='Completed').length} of ${state.items.length} setup items complete</p><button class="link" onclick="go('business')">See setup plan</button></div></section><section class="metric-grid"><div><span>Budget used</span><b>${Math.round(t.committed/state.business.budget*100)}%</b><small>${money(t.committed)} committed</small></div><div><span>Cash paid</span><b>${money(t.paid)}</b><small>${money(t.outstanding)} outstanding</small></div></section><section class="section-head"><div><p class="eyebrow">Attention</p><h2>Next actions</h2></div><button class="link" onclick="go('tasks')">View all</button></section><div class="records">${active.slice(0,3).map(cardItem).join('')}</div><button class="fab" onclick="openAdd()"><b>+</b><span>Quick add</span></button>${nav()}`; }
function business(){ const t=totals(); return `${header(state.business.name, state.business.category)}<section class="dashboard"><div class="dash-card big"><p>Setup forecast</p><h2>${money(t.forecast)}</h2><small>of ${money(state.business.budget)} total budget</small><div class="bar"><i style="width:${Math.min(100,t.forecast/state.business.budget*100)}%"></i></div></div><div class="dash-card"><p>Outstanding</p><h3>${money(t.outstanding)}</h3></div><div class="dash-card"><p>Launch in</p><h3>${Math.max(0,Math.ceil((new Date(state.business.launch)-new Date())/86400000))} days</h3></div></section><section class="section-head"><div><p class="eyebrow">Business setup</p><h2>Modules</h2></div><button class="link" onclick="openAdd()">+ Add item</button></section><div class="modules">${['Compliance','Location','Furniture','Equipment','Team','Products','Branding','Operations','Marketing'].map(m=>{let a=state.items.filter(x=>x.module===m);return `<button onclick="filterModule('${m}')"><span>${m[0]}</span><div><b>${m}</b><small>${a.filter(x=>x.status==='Completed').length}/${a.length || 0} complete</small></div><i>›</i></button>`}).join('')}</div><section class="section-head"><h2>All requirements</h2></section><div class="records">${state.items.map(cardItem).join('')}</div><button class="fab" onclick="openAdd()">＋ <span>Add record</span></button>${nav()}`; }
function tasks(){ const overdue = state.tasks.filter(x=>x.status!=='Done' && new Date(x.due)<new Date()).length; return `${header('Tasks','Stay on top of launch work')}<section class="summary"><b>${state.tasks.filter(x=>x.status!=='Done').length}</b><span>open tasks</span>${overdue?`<em>${overdue} overdue</em>`:''}</section><div class="filters"><button class="selected">All</button><button>To do</button><button>Overdue</button></div><div class="task-list">${state.tasks.map(t=>`<article class="task ${t.status==='Done'?'done':''}"><button class="check" onclick="toggleTask(${t.id})">${t.status==='Done'?'✓':''}</button><div><b>${esc(t.title)}</b><p>${esc(t.module)} · ${t.due}</p></div><span class="chip">${t.status}</span></article>`).join('')}</div><button class="fab" onclick="openTask()">＋ <span>New task</span></button>${nav()}`; }
function vendors(){return `${header('Vendors','Your trusted partners')}<div class="search">⌕ <input placeholder="Search vendors" /></div><section class="section-head"><h2>${state.vendors.length} vendors</h2><button class="link" onclick="openVendor()">+ Add vendor</button></section><div class="vendors">${state.vendors.map(v=>`<article><div class="vendor-mark">${v.name[0]}</div><div><h3>${esc(v.name)}</h3><p>${esc(v.category)} · ${esc(v.person)}</p><a href="tel:${v.phone}">${esc(v.phone)}</a></div><button>⋮</button></article>`).join('')}</div><button class="fab" onclick="openVendor()">＋ <span>Add vendor</span></button>${nav()}`;}
function more(){return `${header('More','Workspace settings')}<div class="more-list">${['Finance overview','Documents','Products & services','Marketing','Business settings','Archived businesses'].map(x=>`<button><span>${x[0]}</span>${x}<i>›</i></button>`).join('')}</div>${nav()}`;}
function render(){ document.querySelector('#app').innerHTML = (screen==='home'?home():screen==='business'?business():screen==='tasks'?tasks():screen==='vendors'?vendors():more()); }
window.go=x=>{screen=x;render();window.scrollTo(0,0)};
window.cycleItem=id=>{const x=state.items.find(x=>x.id===id); const a=['Not started','Quoting','In progress','Completed'];x.status=a[(a.indexOf(x.status)+1)%a.length];save();render()};
window.payment=id=>{const x=state.items.find(x=>x.id===id);const remaining=Math.max(0,(x.committed||x.estimate)-x.paid); if(!x.committed)x.committed=x.estimate; x.paid+=Math.min(remaining,Math.max(1000,Math.round((x.committed-x.paid)/2)));save();render()};
window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);t.status=t.status==='Done'?'To do':'Done';save();render()};
window.filterModule=m=>{screen='business';render(); setTimeout(()=>document.querySelectorAll('.record').forEach(x=>{if(!x.innerHTML.includes(m))x.style.display='none'}),0)};
function modal(title, body){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" onclick="if(event.target===this)this.remove()"><form class="modal" onsubmit="return submitModal(event)"><button type="button" class="close" onclick="this.closest('.modal-wrap').remove()">×</button><h2>${title}</h2>${body}<button class="primary">Save</button></form></div>`)}
window.openAdd=()=>modal('Add setup item',`<label>Item name<input required name="name" placeholder="e.g. POS system" /></label><label>Module<select name="module">${['Compliance','Location','Furniture','Equipment','Team','Products','Branding','Operations','Marketing'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Estimated cost<input name="estimate" type="number" value="0" /></label><input type="hidden" name="kind" value="item" />`);
window.openTask=()=>modal('New task',`<label>Task<input required name="title" placeholder="What needs to happen?" /></label><label>Module<input name="module" value="General" /></label><label>Due date<input type="date" name="due" required /></label><input type="hidden" name="kind" value="task" />`);
window.openVendor=()=>modal('Add vendor',`<label>Company name<input required name="name" /></label><label>Category<input name="category" placeholder="Equipment, interiors..." /></label><label>Contact person<input name="person" /></label><label>Phone<input name="phone" /></label><input type="hidden" name="kind" value="vendor" />`);
window.submitModal=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(f.kind==='item')state.items.unshift({id:Date.now(),name:f.name,module:f.module,status:'Not started',estimate:+f.estimate,committed:0,paid:0,due:'—'}); if(f.kind==='task')state.tasks.unshift({id:Date.now(),title:f.title,module:f.module,due:f.due,status:'To do'});if(f.kind==='vendor')state.vendors.unshift({id:Date.now(),...f});save();e.target.closest('.modal-wrap').remove();render();return false};
render();
